# Generated by Django 4.2.4 on 2023-09-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_program_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='like',
        ),
        migrations.RemoveField(
            model_name='program',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
