# Generated by Django 4.2.4 on 2023-09-16 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pag', to='program.program')),
            ],
            options={
                'verbose_name_plural': 'Details Pagination',
            },
        ),
    ]
