# Generated by Django 4.2.4 on 2023-09-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_programnum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programnum',
            options={'verbose_name_plural': 'ProgramNum'},
        ),
    ]
