# Generated by Django 4.1.4 on 2023-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_alter_programnum_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='counseling',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='deliverance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='speical_program',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
