# Generated by Django 4.1.4 on 2023-10-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weekservice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekservice',
            name='img',
        ),
    ]
