# Generated by Django 4.1.4 on 2023-10-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_weekservice_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekservice',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='weekly'),
        ),
    ]
